# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-28 07:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20171128_0709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='has_binder',
            field=models.BooleanField(default=False),
        ),
    ]
