# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-01 00:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20171128_0710'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='email',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='phone',
            field=models.CharField(max_length=14, null=True),
        ),
    ]
